
quarkus.application.name=Fog
quarkus.banner.enabled=false
quarkus.http.root-path=/
#
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

quarkus.hibernate-orm.schema-management.strategy=none
#quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true
# Pool (Agroal)
quarkus.datasource.jdbc.initial-size=2
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=10
quarkus.datasource.jdbc.acquisition-timeout=5s
#
quarkus.log.category."io.quarkus.config".level=DEBUG
quarkus.log.category."io.agroal.pool".level=DEBUG

# EOF