package tech.nveces.quarkus.fog.app;

import tech.nveces.quarkus.fog.model.Operation;
import jakarta.transaction.Transactional;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import java.util.List;

@Path("/api/operations")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class OperationResource {

    @GET
    public List<Operation> listAll() {
        return Operation.listAll();
    }

    @POST
    @Transactional
    public Response create(Operation operation) {
      if (operation.id != null) {
        operation.id = null; // Ignore any provided ID, it will be generated by the database
        //throw new WebApplicationException("Ignore any provided ID, it will be generated by the database", 422);
      }
      operation.persist();
      return Response.status(Response.Status.CREATED).entity(operation).build();
    }
}
